const cart={};const $=id=>document.getElementById(id);const money=n=>"₹"+Number(n||0).toFixed(0);
const imgMap={"dry":"assets/dry-fruit.jpg","butter":"assets/butter.jpg","chip":"assets/classic-chip.jpg","oats":"assets/oats-raisin.jpg","almond":"assets/almond-cashew.jpg","coconut":"assets/coconut.jpg","double":"assets/double-chocolate.jpg","red":"assets/red-velvet.jpg"};
const fallbackProducts=[
{id:"dry-250",name:"Dry Fruit Cookies - All Flavours",category:"Dry Fruit Cookies",price:299,original_price:399,weight:"250g",image:imgMap.dry,badge:"FRESHLY BAKED"},
{id:"dry-500",name:"Dry Fruit Cookies - All Flavours",category:"Dry Fruit Cookies",price:499,original_price:699,weight:"500g",image:imgMap.almond,badge:"BEST SELLER"},
{id:"bakery-250",name:"Bakery Cookies - All Flavours",category:"Bakery Cookies",price:199,original_price:249,weight:"250g",image:imgMap.butter,badge:"FRESH TODAY"},
{id:"bakery-500",name:"Bakery Cookies - All Flavours",category:"Bakery Cookies",price:399,original_price:499,weight:"500g",image:imgMap.chip,badge:"POPULAR"},
{id:"oats-250",name:"Oats & Raisin Cookies",category:"Oats Cookies",price:249,original_price:349,weight:"250g",image:imgMap.oats,badge:"NEW"},
{id:"coconut-250",name:"Coconut Cookies",category:"Coconut Cookies",price:229,original_price:299,weight:"250g",image:imgMap.coconut,badge:"FRESH BATCH"},
{id:"double-400",name:"Double Chocolate Cookies",category:"Chocolate Cookies",price:249,original_price:399,weight:"400g",image:imgMap.double,badge:"CHOCOLATE LOVER"},
{id:"red-400",name:"Red Velvet Cookies",category:"Red Velvet Cookies",price:249,original_price:399,weight:"400g",image:imgMap.red,badge:"SPECIAL"}
];
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function disc(p){return p.original_price>p.price?Math.round((1-p.price/p.original_price)*100):0}
function imageFor(p){if(p.image_url)return p.image_url;if(p.image)return p.image;const s=((p.name||"")+" "+(p.category||"")).toLowerCase();if(s.includes("red velvet"))return imgMap.red;if(s.includes("double chocolate"))return imgMap.double;if(s.includes("chocolate")||s.includes("chip"))return imgMap.chip;if(s.includes("dry fruit")||s.includes("dry fruits"))return imgMap.dry;if(s.includes("almond")||s.includes("cashew"))return imgMap.almond;if(s.includes("coconut"))return imgMap.coconut;if(s.includes("oat")||s.includes("raisin"))return imgMap.oats;return imgMap.butter}
function addToCart(p){if(!cart[p.id])cart[p.id]={id:p.id,name:p.name,price:+p.price||0,qty:0,weight:p.weight,category:p.category};cart[p.id].qty++;renderCart();openCart()}
function changeQty(id,d){if(!cart[id])return;cart[id].qty+=d;if(cart[id].qty<=0)delete cart[id];renderCart()}
function items(){return Object.values(cart)}function total(){return items().reduce((a,x)=>a+x.price*x.qty,0)}
function openCart(){$("cartOverlay").classList.add("open");renderCart()}function closeCart(e){if(!e||e.target===$("cartOverlay"))$("cartOverlay").classList.remove("open")}
function renderCart(){const a=items();$("cartCount").textContent=a.reduce((n,x)=>n+x.qty,0);$("cartItems").innerHTML=a.length?a.map(x=>`<div class="cartLine"><div><b>${esc(x.name)}</b><small>${esc(x.weight||"")}</small><div class="miniBtns"><button onclick="changeQty('${esc(x.id)}',-1)">−</button><span>${x.qty}</span><button onclick="changeQty('${esc(x.id)}',1)">+</button></div></div><b>${money(x.price*x.qty)}</b></div>`).join(""):`<p>Your cart is empty. Add your favourite cookies first 🍪</p>`;$("cartTotal").textContent=money(total());$("checkoutAmount").textContent=money(total())}
function renderProducts(ps){$("products").innerHTML=ps.map(p=>{const d=disc(p),im=esc(imageFor(p));return `<article class="card"><div class="cookiePhoto"><img src="${im}" alt="${esc(p.name||"Fresh cookies")}" loading="lazy"><span class="freshBadge">${esc(p.badge||"FRESHLY BAKED")}</span></div><div class="cardBody"><h3>${esc(p.name||"Cookie")}</h3><p class="category">${esc(p.weight||"")}${p.weight&&p.category?" · ":""}${esc(p.category||"Freshly baked")}</p><div class="priceRow"><p class="price"><b>${money(p.price)}</b>${p.original_price?`<del>${money(p.original_price)}</del>`:""}</p>${d?`<span class="discount">${d}% OFF</span>`:""}</div><button class="add" onclick='addToCart(${JSON.stringify(p).replace(/</g,"\\u003c")})'>🛒 Add to Cart</button></div></article>`}).join("")}
async function loadProducts(){try{const{data,error}=await sb.from("products").select("*").eq("active",true).order("created_at",{ascending:true});if(error)throw error;const ps=(data||[]).filter(p=>p.price!=null);if(!ps.length)throw Error("No active products");renderProducts(ps);$("status").textContent=`${ps.length} products available`}catch(e){console.warn(e);renderProducts(fallbackProducts);$("status").textContent="8 products available"}}
function validate(){if(!items().length){alert("Please add at least one cookie to your cart.");return false}const n=$("customerName").value.trim(),ph=$("customerPhone").value.replace(/\D/g,""),em=$("customerEmail").value.trim(),ad=$("customerAddress").value.trim(),pin=$("customerPincode").value.trim();if(!n||!ph||!em||!ad||!pin){alert("Please fill name, mobile, email, address and pincode.");return false}if(!/^\d{10}$/.test(ph)){alert("Please enter a valid 10-digit mobile number.");return false}if(!/^\d{6}$/.test(pin)){alert("Please enter a valid 6-digit pincode.");return false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)){alert("Please enter a valid email address.");return false}return true}
async function createOrder(){const p={customer_name:$("customerName").value.trim(),customer_phone:$("customerPhone").value.replace(/\D/g,""),customer_address:$("customerAddress").value.trim(),customer_pincode:$("customerPincode").value.trim(),total_amount:total(),payment_status:"pending",order_status:"new",notes:`Customer email: ${$("customerEmail").value.trim()}`};const{data,error}=await sb.from("orders").insert(p).select("id").single();if(error)throw error;const rows=items().map(x=>({order_id:data.id,product_id:String(x.id),product_name:x.name,weight:x.weight||null,quantity:x.qty,unit_price:x.price,line_total:x.price*x.qty}));const{error:e}=await sb.from("order_items").insert(rows);if(e)throw e;return{orderId:data.id,payload:p}}
async function checkoutAndPay(){if(!validate())return;$("checkoutStatus").textContent="Saving your order…";try{const r=await createOrder();localStorage.setItem("srivari_pending_order",JSON.stringify({orderId:r.orderId,...r.payload,createdAt:new Date().toISOString()}));const url=window.SRIVARI_CONFIG.RAZORPAY_PAYMENT_LINK;if(!url){$("checkoutStatus").textContent=`Order ${r.orderId} saved. Payment link is not configured.`;return}$("checkoutStatus").textContent=`Order ${r.orderId} saved. Opening Razorpay…`;setTimeout(()=>window.open(url,"_blank","noopener"),250)}catch(e){console.error(e);$("checkoutStatus").textContent="Could not save the order.";alert("Order could not be saved. Please check the Supabase orders table and RLS settings.")}}
function sendOrderWhatsApp(){if(!validate())return;const no=(window.SRIVARI_CONFIG.WHATSAPP_NUMBER||"").replace(/\D/g,"");const lines=items().map(x=>`• ${x.name} ${x.weight||""} × ${x.qty} = ${money(x.price*x.qty)}`).join("\n");const text=`SRIVARI COOKIES Order\n\nName: ${$("customerName").value.trim()}\nMobile: ${$("customerPhone").value.trim()}\nEmail: ${$("customerEmail").value.trim()}\nAddress: ${$("customerAddress").value.trim()}\nPincode: ${$("customerPincode").value.trim()}\n\n${lines}\n\nTotal: ${money(total())}`;window.open(`https://wa.me/${no}?text=${encodeURIComponent(text)}`,"_blank","noopener")}
$("year").textContent=new Date().getFullYear();$("emailLink").href=`mailto:${window.SRIVARI_CONFIG.CONTACT_EMAIL}`;$("waLink").href=`https://wa.me/${window.SRIVARI_CONFIG.WHATSAPP_NUMBER}`;renderProducts(fallbackProducts);renderCart();loadProducts();