const products=[
{id:'almond',name:'Almond Cashew Cookies',weight:'250g',price:299,mrp:399,image:'assets/almond-cashew.jpg',badge:'BEST SELLER'},
{id:'butter',name:'Butter Cookies',weight:'250g',price:199,mrp:299,image:'assets/butter.jpg',badge:'FRESHLY BAKED'},
{id:'chip',name:'Classic Choco Chip Cookies',weight:'250g',price:249,mrp:349,image:'assets/classic-chip.jpg',badge:'POPULAR'},
{id:'coconut',name:'Coconut Cookies',weight:'250g',price:229,mrp:329,image:'assets/coconut.jpg',badge:'FRESH TODAY'},
{id:'double',name:'Double Chocolate Cookies',weight:'250g',price:249,mrp:399,image:'assets/double-chocolate.jpg',badge:'RICH & FUDGY'},
{id:'dry',name:'Dry Fruit Cookies',weight:'250g',price:299,mrp:399,image:'assets/dry-fruit.jpg',badge:'PREMIUM'},
{id:'oats',name:'Oats Raisin Cookies',weight:'250g',price:249,mrp:349,image:'assets/oats-raisin.jpg',badge:'HEALTHY CHOICE'},
{id:'red',name:'Red Velvet Cookies',weight:'250g',price:279,mrp:379,image:'assets/red-velvet.jpg',badge:'NEW'}];
let cart=JSON.parse(localStorage.getItem('srivariCart')||'[]');
const grid=document.getElementById('productGrid');
function off(p){return Math.round((1-p.price/p.mrp)*100)}
function renderProducts(){grid.innerHTML=products.map(p=>`<article class="card"><div class="photo"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge">${p.badge}</span></div><div class="info"><h3>${p.name}</h3><div class="weight">${p.weight}</div><div class="priceRow"><div class="price">₹${p.price}<span class="mrp">₹${p.mrp}</span></div><span class="off">${off(p)}% OFF</span></div><button class="add" onclick="addToCart('${p.id}')">🛒 Add to Cart</button></div></article>`).join('')}
function addToCart(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});saveCart();openDrawer()}
function saveCart(){localStorage.setItem('srivariCart',JSON.stringify(cart));renderCart();document.getElementById('cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function renderCart(){const box=document.getElementById('cartItems');if(!cart.length){box.innerHTML='<div class="empty">Your cart is empty.<br>Add some cookies ❤️</div>';document.getElementById('cartTotal').textContent='₹0';return}let total=0;box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="cartLine"><img src="${p.image}"><div><b>${p.name}</b><small>₹${p.price} × ${i.qty}</small></div><div class="qty"><button onclick="changeQty('${p.id}',-1)">−</button> ${i.qty} <button onclick="changeQty('${p.id}',1)">+</button></div></div>`}).join('');document.getElementById('cartTotal').textContent='₹'+total}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart()}
function openDrawer(){document.getElementById('drawer').classList.add('open');document.getElementById('shade').classList.add('open')}
function closeDrawer(){document.getElementById('drawer').classList.remove('open');document.getElementById('shade').classList.remove('open')}
document.getElementById('openCart').onclick=openDrawer;document.getElementById('closeCart').onclick=closeDrawer;document.getElementById('shade').onclick=closeDrawer;
document.getElementById('checkout').addEventListener('submit',async e=>{e.preventDefault();if(!cart.length)return alert('Please add cookies to cart.');const name=document.getElementById('cname').value.trim(),phone=document.getElementById('phone').value.trim(),email=document.getElementById('email').value.trim(),address=document.getElementById('address').value.trim(),pincode=document.getElementById('pincode').value.trim();const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+p.price*i.qty},0);let saved=false;try{if(window.supabaseClient){const r=await window.supabaseClient.from('orders').insert({customer_name:name,customer_phone:phone,customer_address:address,customer_pincode:pincode,total_amount:total,payment_status:'awaiting_payment',order_status:'new',notes:email}).select().single();if(!r.error){for(const i of cart){const p=products.find(x=>x.id===i.id);await window.supabaseClient.from('order_items').insert({order_id:r.data.id,product_id:p.id,product_name:p.name,weight:p.weight,quantity:i.qty,unit_price:p.price,line_total:p.price*i.qty})}saved=true}}}catch(err){}const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `${p.name} (${p.weight}) x${i.qty} = ₹${p.price*i.qty}`}).join('\n');const msg=`SRIVARI COOKIES ORDER\n\nName: ${name}\nMobile: ${phone}\nEmail: ${email}\nAddress: ${address}\nPincode: ${pincode}\n\n${lines}\n\nTotal: ₹${total}\nOrder saved: ${saved?'Yes':'WhatsApp only'}`;window.open('https://wa.me/'+window.SRIVARI_CONFIG.WHATSAPP_NUMBER+'?text='+encodeURIComponent(msg),'_blank');alert('Order saved as Awaiting Payment. Complete payment through the Razorpay link; payment status will require verification until a Razorpay webhook is connected.');if(window.SRIVARI_CONFIG.RAZORPAY_PAYMENT_LINK)window.open(window.SRIVARI_CONFIG.RAZORPAY_PAYMENT_LINK,'_blank')});
renderProducts();saveCart();
