-- Run this once in Supabase SQL Editor.
-- This creates the order tables needed by the SRIVARI COOKIES website.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_pincode text not null,
  total_amount numeric(12,2) not null check (total_amount >= 0),
  payment_status text not null default 'pending'
    check (payment_status in ('pending','paid','failed','refunded')),
  order_status text not null default 'new'
    check (order_status in ('new','confirmed','packed','shipped','delivered','cancelled')),
  razorpay_order_id text,
  razorpay_payment_id text,
  notes text
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  weight text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0)
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Customer checkout needs INSERT access.
drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "public can create order items" on public.order_items;
create policy "public can create order items"
on public.order_items for insert
to anon, authenticated
with check (true);

-- Do NOT create public SELECT/UPDATE policies for orders.
-- Admin access should use an authenticated admin account or a server-side service role.
